### ISSUE TITLE
KeyError: 'gptj' with transformers

### ISSUE THREAD

**Issue by kazeto111** [kingoflolz/mesh-transformer-jax#107]
I implemented 
```
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-j-6B")
model = AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-j-6B")
```
just following the indication of transformes https://huggingface.co/EleutherAI/gpt-j-6B

Then I got the error like below
```
2021-08-24 08:17:25.630477: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 826/826 [00:00<00:00, 839kB/s]
Traceback (most recent call last):
  File "pull_gptj_server.py", line 127, in <module>
    init_ai_model()
  File "pull_gptj_server.py", line 59, in init_ai_model
    tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-j-6B")
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 534, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/auto/configuration_auto.py", line 452, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
KeyError: 'gptj'
```

even after removing the  `tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-j-6B")`
I got the error
```
2021-08-24 08:18:11.244477: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 665/665 [00:00<00:00, 614kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 1.04M/1.04M [00:00<00:00, 3.32MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 456k/456k [00:00<00:00, 1.40MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 1.36M/1.36M [00:00<00:00, 3.01MB/s]
Traceback (most recent call last):
  File "pull_gptj_server.py", line 127, in <module>
    init_ai_model()
  File "pull_gptj_server.py", line 60, in init_ai_model
    model = AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-j-6B")
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/auto/auto_factory.py", line 379, in from_pretrained
    pretrained_model_name_or_path, return_unused_kwargs=True, **kwargs
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/auto/configuration_auto.py", line 452, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
KeyError: 'gptj'
```

Then how can I solve this problem?

Thank you so much

**Comment by kingoflolz** [comment]
The huggingface support has not been merged yet (https://github.com/huggingface/transformers/pull/13022), and please take support requests for the huggingface model to their repo (https://github.com/huggingface/transformers)
