### ISSUE TITLE
Save failed during checkpoint saving function call

### ISSUE THREAD

**Issue by VishalSharmavj** [kingoflolz/mesh-transformer-jax#154]
Earlier I was facing error in 
```
with open(f"gs://{bucket}/{path}/meta.json", "r")
```
as it was saying 404 blob not found (I still don't know why the exception was not able to create one itself in the bucket). Thus I created a meta.json with below content and saved it. 

```
{"step": 0,
"checkpoints": [],
"aux": {}
}

```
Now the device_train.py code is performing till the last step and crashes with save failed error as,

```
key shape (8, 2)
in shape (1, 15)
dp 1
mp 8
Total parameters: 6053381344
loading network
read from disk/gcs in 557.68s
network loaded in 602.296s
compiling train fn
Train fn compiled in 108.089s
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'
wandb: W&B syncing is set to `offline` in this directory.
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
saving a checkpoint for step 1
save failed, trying again
save failed, trying again
save failed, trying again
save failed 3 times, exiting
Traceback (most recent call last):
  File "device_train.py", line 288, in <module>
    save(network, step, bucket, model_dir,
  File "device_train.py", line 73, in save
    write_ckpt(network.state, f"gs://{bucket}/{path}/step_{step}/", shard_id)
  File "/home/12vis/mesh-copy/mesh_transformer/checkpoint.py", line 78, in write_ckpt
    list((p.imap_unordered(write_fn, enumerate(cpu_flattened_chunked))))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/12vis/mesh-copy/mesh_transformer/checkpoint.py", line 49, in write
    raise Exception("save failed")
Exception: save failed

```

Below is my config file with which I'm trying to train a small set of training data and no validation data, Am I missing something?
```
{
  "layers": 28,
  "d_model": 4096,
  "n_heads": 16,
  "n_vocab": 50400,
  "norm": "layernorm",
  "pe": "rotary",
  "pe_rotary_dims": 64,

  "seq": 15,
  "cores_per_replica": 8,
  "per_replica_batch": 1,
  "gradient_accumulation_steps": 16,

  "warmup_steps": 1,
  "anneal_steps": 12,
  "lr": 5e-5,
  "end_lr": 1e-5,
  "weight_decay": 0.1,
  "total_steps": 13,

  "tpu_size": 8,

  "bucket": "6b-training",
  "model_dir": "final-checkpoints",

  "train_set": "example.train.index",
  
  "eval_harness_tasks": [
    "lambada",
    "piqa",
    "hellaswag",
    "winogrande",
    "mathqa",
    "pubmedqa"
  ],

  "val_batches": 209,
  "val_every": 500,
  "ckpt_every": 500,
  "keep_every": 10000,

  "name": "GPT3_6B",
  "wandb_project": "mesh-transformer-jax",
  "comment": ""
}
```

**Comment by kingoflolz** [comment]
Could you print out the exception caught here? https://github.com/kingoflolz/mesh-transformer-jax/blob/master/mesh_transformer/checkpoint.py#L45

**Comment by Leah-LJX** [comment]
I have encountered the same problem. I have tried to give my tpu-vm the access permissions to my bucket, but I still do not solve it. Maybe I didn't set it successfully, but I have tried any kinds of permission. 
May I ask if anyone has configured successfully? Can you share it?
The following is my error:

`Traceback (most recent call last):
  File "device_train.py", line 302, in <module>
    save(network, step, bucket, model_dir,
  File "device_train.py", line 62, in save
    with open(f"gs://{bucket}/{path}/meta.json", "w") as f:
  File "/usr/local/lib/python3.8/dist-packages/smart_open/smart_open_lib.py", line 235, in open
    binary = _open_binary_stream(uri, binary_mode, transport_params)
  File "/usr/local/lib/python3.8/dist-packages/smart_open/smart_open_lib.py", line 398, in _open_binary_stream
    fobj = submodule.open_uri(uri, mode, transport_params)
  File "/usr/local/lib/python3.8/dist-packages/smart_open/gcs.py", line 105, in open_uri
    return open(parsed_uri['bucket_id'], parsed_uri['blob_id'], mode, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/smart_open/gcs.py", line 146, in open
    fileobj = Writer(
  File "/usr/local/lib/python3.8/dist-packages/smart_open/gcs.py", line 427, in __init__
    self._resumable_upload_url = self._blob.create_resumable_upload_session()
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/storage/blob.py", line 2728, in create_resumable_upload_session
    _raise_from_invalid_response(exc)
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/storage/blob.py", line 3936, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.Forbidden: 403 POST https://storage.googleapis.com/upload/storage/v1/b/mybucket/o?uploadType=resumable: {
  "error": {
    "code": 403,
    "message": "Access denied.",
    "errors": [
      {
        "message": "Access denied.",
        "domain": "global",
        "reason": "forbidden"
      }
    ]
  }
}
: ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.CREATED: 201>)
`
I hope someone can reply to me, thank you very much!

**Comment by ljj430** [comment]
> 

It is because you do not authenticate Google Cloud API when you access Google Cloud Storage. You can follow [link](https://cloud.google.com/docs/authentication/getting-started) to set authentication to fix this issue.
