### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by DimIsaev** [kingoflolz/mesh-transformer-jax#205]
python3 device.serve.py 

```
Traceback (most recent call last):
  File "device_serve.py", line 11, in <module>
    from mesh_transformer import util
  File "/home/dim/mesh-transformer-jax/mesh_transformer/util.py", line 36, in <module>
    class ClipByGlobalNormState(OptState):
  File "/usr/lib/python3.8/typing.py", line 317, in __new__
    raise TypeError(f"Cannot subclass {cls!r}")
TypeError: Cannot subclass <class 'typing._SpecialForm'>
```

**Comment by samyakai** [comment]
@DimIsaev How did you solve the error? I am getting the same error while fine tuning
