### ISSUE TITLE
TypeError: Cannot subclass <class 'typing._SpecialForm'> while fine tuning

### ISSUE THREAD

**Issue by samyakai** [kingoflolz/mesh-transformer-jax#222]
I am trying to fine tune gpt-j on custom data using TPU. When I try to run the "device_train.py" file using the mentioned command:  "python3 device_train.py --config=YOUR_CONFIG.json --tune-model-path=gs://YOUR-BUCKET/step_383500/", I get this error:

Traceback (most recent call last):
  File "device_train.py", line 13, in <module>
    from mesh_transformer import util
  File "/home/shreyjain/mesh-transformer-jax/mesh_transformer/util.py", line 36, in <module>
    class ClipByGlobalNormState(OptState):
  File "/usr/lib/python3.8/typing.py", line 317, in __new__
    raise TypeError(f"Cannot subclass {cls!r}")
TypeError: Cannot subclass <class 'typing._SpecialForm'>

OS = Ubuntu 20.04
TPU V3-8

I have no idea what this error means. Any help would be appreciated! 
Thank you.

**Comment by Jaggu798** [comment]
Getting the same issue not able to solve 
Please help us
Thank you

**Comment by mosmos6** [comment]
Maybe this works.

`pip install dm-haiku==0.0.5`
and put optax back to the default version.

**Comment by shrey10926** [comment]
@mosmos6  Nope it gives the same error

**Comment by anon-mouse-1** [comment]
https://github.com/kingoflolz/mesh-transformer-jax/issues/202#issuecomment-1050887576
Please follow this solution! It works.

**Comment by Jaggu798** [comment]
@anon-mouse-1 which v2 version of TPU should i use? There are 2 options for TPU namely TPU VM architecture and tpu node architecture.

**Comment by Tylersuard** [comment]
After the 5th error I just gave up on this notebook.

**Comment by samyakai** [comment]
@Tylersuard Yes. Also no one is providing a solution to the errors which is a shame as I really want to train on TPU as opposed to a GPU

**Comment by CoaLee** [comment]
@samyakai
Try `pip install optax==0.0.6 chex==0.0.6`.

I've been trying using this on GPUs, by directly running `device_train.py`(slightly modified to rip away TPU-specific part). Got stuck at similar error cases, and just succeeded with toy data.

I guess the authors didn't notice some breaking changes inside these libraries except `jax` and `jaxlib`.

Versions are chosen by comparing commit dates of the libraries.
- [jax 0.2.12](https://github.com/google/jax/tree/jax-v0.2.12) (Apr 2, 2021)
- [optax v0.0.6](https://github.com/deepmind/optax/tree/v0.0.6) (Mar 26, 2021)
- [chex v0.0.6](https://github.com/deepmind/chex/tree/v0.0.6) (Mar 26, 2021)

Hope it works.

---
## Some Details
### Environment
- GPU: A100
- Nvidia driver version: 470.57.52
- CUDA version: 11.x
- Base docker image: `tensorflow/tensorflow:2.6.0` 

### Error messages I encountered
1. `ClipByGlobalNormState` thing. I think it's basically the same error as yours, only different on python version.
    ```
    Traceback (most recent call last):                                                     
      File "device_train.py", line 14, in <module>                                         
        from mesh_transformer import util                                                  
      File "/workspace/mesh-transformer-jax/mesh_transformer/util.py", line 36, in <module>
        class ClipByGlobalNormState(OptState):                                             
      File "/usr/lib/python3.6/typing.py", line 733, in __new__                            
        self = super().__new__(cls, parameters, origin, *args, _root=_root)                
      File "/usr/lib/python3.6/typing.py", line 207, in __new__                            
        self = super().__new__(cls, *args, **kwds)                                         
      File "/usr/lib/python3.6/typing.py", line 178, in __new__                            
        raise TypeError("Cannot subclass %r" % cls)
    TypeError: Cannot subclass typing.Union
    ```
2. `KeyArray` stuff after solving the above with other way around.
    ```
    ...
    AttributeError: 'jax.random' object has no attribute 'KeyArray'
    ```

**Comment by dhruv2601** [comment]
Downgrading optax worked for me to get rid of this error.

pip install optax==0.0.9

**Comment by mosmos6** [comment]
> [#202 (comment)](https://github.com/kingoflolz/mesh-transformer-jax/issues/202#issuecomment-1050887576) Please follow this solution! It works.

In addition to this, 
`pip install chex==0.1.2`
`pip install jaxlib==0.1.74`
`pip install dm-haiku==0.0.5`

and it worked for me.
