### ISSUE TITLE
TypeError: don't know how to handle uri None

### ISSUE THREAD

**Issue by Metroman123** [kingoflolz/mesh-transformer-jax#48]
Whenever I try to run device_sample or device_train I get the following error here:

```
**Traceback (most recent call last):
  File "device_sample.py", line 30, in <module>
    params = json.load(open(args.config))
  File "/home/nin/.local/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 235, in open
    binary = _open_binary_stream(uri, binary_mode, transport_params)
  File "/home/nin/.local/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 394, in _open_binary_stream
    raise TypeError("don't know how to handle uri %s" % repr(uri))
TypeError: don't know how to handle uri None**

```
I have all the required libraries, is there a config file that I am missing somewhere?

**Comment by kingoflolz** [comment]
You need to pass in the config file with --config
