### ISSUE TITLE
Jax TPU Issue

### ISSUE THREAD

**Issue by Alexmhack** [kingoflolz/mesh-transformer-jax#59]
Hi @kingoflolz, amazing work!!

I am trying to test the model on TPU VM using the step_383500/ data.

On following the steps mentioned in [jax-quickstart-tpu-vm](https://cloud.google.com/tpu/docs/jax-quickstart-tpu-vm) and then running `jax.devices()` returns correct output which is

```
[TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0), TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1), TpuDevice(id=2, process_index=0, coords=(1,0,0), core_on_chip=0), TpuDevice(id=3, process_index=0, coords=(1,0,0), core_on_chip=1), TpuDevice(id=4, process_index=0, coords=(0,1,0), core_on_chip=0), TpuDevice(id=5, process_index=0, coords=(0,1,0), core_on_chip=1), TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0), TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)]
```

After that when I clone your repo and run `pip install -r requirements.txt` and then run `pip install jax==0.2.12` as you mentioned in your fine tune docs, but It gives this error,

```
2021-07-18 05:15:21.807145: F external/org_tensorflow/tensorflow/core/tpu/tpu_executor_init_fns.inc:110] TpuTransferManager_ReadDynamicShapes not available in this library.
Aborted (core dumped)
```

so I run this from [jax-quickstart-tpu-vm](https://cloud.google.com/tpu/docs/jax-quickstart-tpu-vm#install_jax_on_your_cloud_tpu_vm) docs,

```
pip install "jax[tpu]>=0.2.16" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
```

after which `jax.devices()` gives this output

```
>>> import jax
>>> jax.devices()
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
[CpuDevice(id=0)]
```

Somehow `jax` fails to detect the TPU, don't know what's the issue, I am running Google Cloud's TPU VM v3-8 with v2-alpha software version. Would really appreciate your help.

**Comment by kingoflolz** [comment]
Try using this script to install your dependencies https://github.com/kingoflolz/mesh-transformer-jax/blob/master/scripts/init_ray.sh

**Comment by Alexmhack** [comment]
`init_ray.sh` installs out of the virtualenv but even after that running the below code sometime runs and sometimes not like If I ssh into vm and the very firstly I check the `jax.devices_count()` then it shows **8** but if I exit and run it again then it goes back to the `WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)` or simply gets stuck and doesn't do anything.

Apart from this when running the `infer` method, it throws this error,

```
Traceback (most recent call last):
  File "mesh-transformer-jax/inference.py", line 115, in <module>
    print(infer(context))
  File "mesh-transformer-jax/inference.py", line 97, in infer
    output = network.generate(
  File "/home/Pranav/mesh-transformer-jax/mesh_transformer/transformer_shard.py", line 337, in generate
    return self.generate_xmap(self.state,
  File "/home/Pranav/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 583, in fun_mapped
    in_axes_flat = flatten_axes("xmap in_axes", in_tree, in_axes)
  File "/home/Pranav/.local/lib/python3.8/site-packages/jax/api_util.py", line 278, in flatten_axes
    raise ValueError(f"{name} specification must be a tree prefix of the "
ValueError: xmap in_axes specification must be a tree prefix of the corresponding value, got specification (FrozenDict({'shard': 0}), FrozenDict({'batch': 0}), FrozenDict({'batch': 0}), FrozenDict({'batch': 0}), FrozenDict({'batch': 0}), FrozenDict({'batch': 0})) for value tree PyTreeDef(({'opt_state': CustomNode(namedtuple[<class 'optax._src.transform.ScaleState'>], []), 'params': CustomNode(<class 'haiku._src.data_structures.FlatMap'>[PyTreeDef({'causal_transformer_shard/~/embedding_shard/~/linear': CustomNode(<class 'haiku._src.data_structures.FlatMap'>[PyTreeDef({'b': *, 'w': *})], [*, *]), 'causal_transformer_shard/~/layer_0/~/linear': CustomNode(<class 'haiku._src.data_structures.FlatMap'>[PyTreeDef({'w': *})], [*]), 'causal_transformer_shard/~/layer_0/~/linear_1': CustomNode(<class 'haiku._src.data_structures.FlatMap'>[PyTreeDef({'w': *})], [*]), 'causal_transformer_shard/~/layer_0/~/linear_2': CustomNode(<class 'haiku._src.data_structures.FlatMap'>[PyTreeDef({'w': *})], [*]), 'causal_transformer_shard/~/layer_0/~/linear_3': CustomNode(<class 'haiku._src.data_structures.FlatMap'>[PyTreeDef({'w': *})], [*]), 'causal_transformer_shard/~/layer_0/~/linear_4': CustomNode(<class 'haiku._src.data_structures.FlatMap'>[PyTreeDef({'b': *, 'w': *})], [*, *]), 'causal_transformer_shard/~/layer_0/~/linear_5': CustomNode(<class 'haiku._src.data_structures.FlatMap'>[PyTreeDef({'b': *, 'w': *})], .............

# let me know if you need the whole error
```

Here is my infer method copied from the collab,

```
def infer(context, top_p=0.9, temp=1.0, gen_len=512):
    tokens = tokenizer.encode(context)

    provided_ctx = len(tokens)
    pad_amount = seq - provided_ctx

    padded_tokens = np.pad(tokens, ((pad_amount, 0),)).astype(np.uint32)
    batched_tokens = np.array([padded_tokens] * total_batch)
    length = np.ones(total_batch, dtype=np.uint32) * len(tokens)

    start = time.time()
    output = network.generate(
        batched_tokens, length, gen_len, {"top_p": np.ones(total_batch) * top_p, "temp": np.ones(total_batch) * temp}
    )

    samples = []
    decoded_tokens = output[1][0]

    for o in decoded_tokens[:, :, 0]:
      samples.append(f"\033[1m{context}\033[0m{tokenizer.decode(o)}")

    print(f"completion done in {time.time() - start:06}s")
    return samples
```

**Comment by kingoflolz** [comment]
When you have multiple python instances running at the same time, only the first one that imports jax and is still running will be able to use the TPU. I'm not sure why your infer code is erroring out, can you run the notebook verbatim on the tpu?

**Comment by Alexmhack** [comment]
Ok makes sense. 

Have made some progress with the above error, now this error comes when running the infer function,

```
Traceback (most recent call last):
  File "mesh-transformer-jax/inference.py", line 115, in <module>
    print(infer(context))
  File "mesh-transformer-jax/inference.py", line 97, in infer
    output = network.generate(
  File "/home/Pranav/mesh-transformer-jax/mesh_transformer/transformer_shard.py", line 328, in generate
    return self.generate_xmap(self.state,
  File "/home/Pranav/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 615, in fun_mapped
    out_flat = xmap_p.bind(
  File "/home/Pranav/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 818, in bind
    return core.call_bind(self, fun, *args, **params)  # type: ignore
  File "/home/Pranav/.local/lib/python3.8/site-packages/jax/core.py", line 1551, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/Pranav/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 821, in process
    return trace.process_xmap(self, fun, tracers, params)
  File "/home/Pranav/.local/lib/python3.8/site-packages/jax/core.py", line 606, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/Pranav/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 646, in xmap_impl
    xmap_callable = make_xmap_callable(
  File "/home/Pranav/.local/lib/python3.8/site-packages/jax/linear_util.py", line 262, in memoized_fun
    ans = call(fun, *args)
  File "/home/Pranav/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 673, in make_xmap_callable
    _check_out_avals_vs_out_axes(out_avals, out_axes, global_axis_sizes)
  File "/home/Pranav/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 1454, in _check_out_avals_vs_out_axes
    raise TypeError(f"One of xmap results has an out_axes specification of "
TypeError: One of xmap results has an out_axes specification of ['batch', ...], but is actually mapped along more axes defined by this xmap call: shard
```

**Comment by kingoflolz** [comment]
You must make sure jax.__version__ is equal to 0.2.12, reopen if that is actually the case

**Comment by hugbubby** [comment]
> You must make sure `jax.__version__` is equal to 0.2.12, reopen if that is actually the case

Can you check the initial post? 0.2.12 immediately aborts.
