### ISSUE TITLE
Device_train execution halts

### ISSUE THREAD

**Issue by paramjeet2021** [kingoflolz/mesh-transformer-jax#61]
I am running device_train.py to train a custom model on a smaller dataset. I have only 4-5 txt files and converted txt files into the tfrecord using the code given in the below link

https://github.com/EleutherAI/gpt-neo/blob/master/data/create_tfrecords.py

I get only 2-3 tfrecords files. 

Now, When I execute the device_train.py on these  tfrecords files, it runs for 15-20 minutes and then shows following error.

Traceback (most recent call last):
  File "device_train.py", line 268, in <module>
    train_step(network, train_dataset.get_samples())
  File "/home/paramjeetsingh80/mesh-transformer-jax/tfrecord_loader.py", line 70, in get_samples
    return self.get_samples()
  File "/home/paramjeetsingh80/mesh-transformer-jax/tfrecord_loader.py", line 70, in get_samples
    return self.get_samples()
  File "/home/paramjeetsingh80/mesh-transformer-jax/tfrecord_loader.py", line 70, in get_samples
    return self.get_samples()
  [Previous line repeated 952 more times]
  File "/home/paramjeetsingh80/mesh-transformer-jax/tfrecord_loader.py", line 66, in get_samples
    return next(self.sample_fn)
  File "/home/paramjeetsingh80/mesh-transformer-jax/tfrecord_loader.py", line 44, in sample_once
    file = tf.data.TFRecordDataset(i, compression_type=compression).map(self.parse_fn, num_parallel_calls=tf.data.AUTOTUNE)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1927, in map
    return ParallelMapDataset(
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4522, in __init__
    self._map_func = StructuredFunctionWrapper(
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3712, in __init__
    self._function = fn_factory()
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3134, in get_concrete_function
    graph_function = self._get_concrete_function_garbage_collected(
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3100, in _get_concrete_function_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3279, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3687, in wrapped_fn
    ret = wrapper_helper(*args)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3617, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.autograph.impl.api.StagingError: in user code:

    /home/paramjeetsingh80/mesh-transformer-jax/tfrecord_loader.py:85 tf_parse  *
        parsed_features = tf.io.parse_single_example(example_proto, features)
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206 wrapper  **
        return target(*args, **kwargs)
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/ops/parsing_ops.py:452 parse_single_example_v2
        return parse_example_v2(serialized, features, example_names, name)
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/ops/parsing_ops.py:314 parse_example_v2
        outputs = _parse_example_raw(serialized, example_names, params, name=name)
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/ops/parsing_ops.py:350 _parse_example_raw
        outputs = gen_parsing_ops.parse_example_v2(
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/ops/gen_parsing_ops.py:748 parse_example_v2
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py:517 _apply_op_helper
        values = ops.convert_to_tensor(
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py:163 wrapped
        return func(*args, **kwargs)
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:1566 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py:339 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py:264 constant
        return _constant_impl(value, dtype, shape, name, verify_shape=False,
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py:286 _constant_impl
        const_tensor = g._create_op_internal(  # pylint: disable=protected-access
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py:599 _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:3557 _create_op_internal
        ret = Operation(
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:2057 __init__
        tensor = Tensor._create_with_tf_output(self, i, output_type, tf_output)  # pylint: disable=protected-access
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:405 _create_with_tf_output
        ret = Tensor(op, value_index, dtype)
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:381 __init__
        self._dtype = dtypes.as_dtype(dtype)
    /home/paramjeetsingh80/.local/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py:633 as_dtype
        return _ANY_TO_TF[type_value]

    RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by kingoflolz** [comment]
How big are the files? The code is not really designed to run for more than a few epochs

**Comment by paramjeet2021** [comment]
Files are not really big. Max size is 20KB. 

Is there any requirements of number of tfrecords files to train on device_train.py? Does it work for 1 tfrecord as well or it needs some minimum number of files?

**Comment by kingoflolz** [comment]
I would strongly suggest you either get more data. With smaller datasets, its much better to only use a single tfrecord file. This is probably still a bug, but I'm not planning on fixing it as training for that many epochs/with that little data is not an intended usecase.

**Comment by paramjeet2021** [comment]
How many minimum txt files I should supply?
Does this code work with a single tfrecord?

**Comment by kingoflolz** [comment]
With small datasets, I suggest adding everthing to a single text file and create a single tfrecord. You should have at least a few megabytes of text, ideally much more.
