### ISSUE TITLE
Issue while importing trained model

### ISSUE THREAD

**Issue by paramjeet2021** [kingoflolz/mesh-transformer-jax#64]
I am using colab_demo to generate content on my V3-8 machine. Earlier I had trained my custom model with custom dataset. 
I had converted text files to tfrecords and then created a model using device_train.py. 

Now when I executing the code in the colab_demo which is pointing to the my trained model repo in GS bucket. Then I get the following errror:

```
Traceback (most recent call last):
    network.state = read_ckpt(network.state, "gs://agencyq-gptj6b/trained-model/step_5/", devices.shape[1])
  File "/home/paramjeetsingh80/mesh-transformer-jax/mesh_transformer/checkpoint.py", line 147, in read_ckpt
    assert x.shape == old.shape, f"Incompatible checkpoints {x.shape} vs {old.shape}"
AssertionError: Incompatible checkpoints (8,) vs (8, 4096)
```

**Comment by kingoflolz** [comment]
you need to use slim_model.py to generate a slim checkpoint for colab inference

**Comment by paramjeet2021** [comment]
Does slim_model.py converts model checkpoint in the directory to slim model checkpoint and that would be consumed by the colab?

**Comment by kingoflolz** [comment]
it must be run on a tpuvm, and reads/writes to a cloud bucket.

**Comment by paramjeet2021** [comment]
I had converted the model into _slim format, not _slim_f16. 

Now, when I execute the colab code and I get below error

```
loading netwrok from the Google storage
read from disk/gcs in 107.5s
Traceback (most recent call last):
  File "content_generation.py", line 90, in <module>
    print(infer(top_p=top_p, temp=temp, gen_len=512, context=context)[0])
  File "content_generation.py", line 77, in infer
    output = network.generate(batched_tokens, length, gen_len, {"top_p": np.ones(total_batch) * top_p, "temp": np.ones(total_batch) * temp})
  File "/home/paramjeetsingh80/mesh-transformer-jax/mesh_transformer/transformer_shard.py", line 309, in generate
    return self.generate_xmap(self.state,
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 615, in fun_mapped
    out_flat = xmap_p.bind(
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 818, in bind
    return core.call_bind(self, fun, *args, **params)  # type: ignore
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/core.py", line 1551, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 821, in process
    return trace.process_xmap(self, fun, tracers, params)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/core.py", line 606, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 646, in xmap_impl
    xmap_callable = make_xmap_callable(
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/linear_util.py", line 262, in memoized_fun
    ans = call(fun, *args)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 673, in make_xmap_callable
    _check_out_avals_vs_out_axes(out_avals, out_axes, global_axis_sizes)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 1454, in _check_out_avals_vs_out_axes
    raise TypeError(f"One of xmap results has an out_axes specification of "
TypeError: One of xmap results has an out_axes specification of ['batch', ...], but is actually mapped along more axes defined by this xmap call: shard
```
