### ISSUE TITLE
RuntimeError: Resource exhausted: Failed to allocate request for 32.00MiB (33554432B) on device ordinal 0

### ISSUE THREAD

**Issue by tomar-amit** [kingoflolz/mesh-transformer-jax#66]
Hi, 
I am facing this issue while running the "mesh-transformer-jax/**resharding_example.py**"
**RuntimeError: Resource exhausted: Failed to allocate request for 32.00MiB (33554432B) on device ordinal 0**

2021-07-21 16:15:16.513776: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1981] Execution of replica 0 failed: Resource exhausted: Failed to allocate request for 32.00MiB (33554432B) on device ordinal 0
Traceback (most recent call last):
  File "resharding_example.py", line 47, in <module>
    network = CausalTransformer(params)
  File "/drive4/user1/GPT_J/mesh-transformer-jax/mesh_transformer/transformer_shard.py", line 272, in __init__
    self.state = self.init_xmap(jnp.array(key.take(mp_per_host)), x)
  File "/drive4/user1/GPT_J/venv/lib/python3.8/site-packages/jax/experimental/maps.py", line 516, in fun_mapped
    out_flat = xmap_p.bind(
  File "/drive4/user1/GPT_J/venv/lib/python3.8/site-packages/jax/experimental/maps.py", line 652, in bind
    return core.call_bind(self, fun, *args, **params)  # type: ignore
  File "/drive4/user1/GPT_J/venv/lib/python3.8/site-packages/jax/core.py", line 1393, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/drive4/user1/GPT_J/venv/lib/python3.8/site-packages/jax/experimental/maps.py", line 655, in process
    return trace.process_xmap(self, fun, tracers, params)
  File "/drive4/user1/GPT_J/venv/lib/python3.8/site-packages/jax/core.py", line 600, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/drive4/user1/GPT_J/venv/lib/python3.8/site-packages/jax/experimental/maps.py", line 539, in xmap_impl
    return make_xmap_callable(fun, name, in_axes, out_axes_thunk, donated_invars, global_axis_sizes,
  File "/drive4/user1/GPT_J/venv/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 1130, in execute_replicated
    out_bufs = compiled.execute_sharded_on_local_devices(input_bufs)
RuntimeError: Resource exhausted: Failed to allocate request for 32.00MiB (33554432B) on device ordinal 0

**System Config mention below:**
nvidia-smi 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:02:00.0 Off |                  N/A |
| 10%   42C    P8    21W / 250W |      1MiB / 11177MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

RAM: 62G
export XLA_PYTHON_CLIENT_PREALLOCATE=false XLA_PYTHON_CLIENT_ALLOCATOR=platform
Python 3.8.7

**Comment by kingoflolz** [comment]
You need a GPU with more vram (at least 19gb), see https://github.com/kingoflolz/mesh-transformer-jax/blob/master/resharding_example.py#L1
