### ISSUE TITLE
when running device_sample.py on my trained model i got this error

### ISSUE THREAD

**Issue by NaveedMaz** [kingoflolz/mesh-transformer-jax#71]
hello once again,
i have trained the model on my dataset thanks to you. but when i now run device_sample.py with the same config file i used to train i got this following error.
```
Traceback (most recent call last):
  File "device_sample.py", line 99, in <module>
    output = network.generate(batched_tokens, length, 512, {"top_p": np.ones(total_batch) * 0.9,
  File "/home/adnanmunye/mesh-transformer-jax/mesh_transformer/transformer_shard.py", line 328, in generate
    return self.generate_xmap(self.state,
  File "/home/adnanmunye/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 613, in fun_mapped
    out_flat = xmap_p.bind(
  File "/home/adnanmunye/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 820, in bind
    return core.call_bind(self, fun, *args, **params)  # type: ignore
  File "/home/adnanmunye/.local/lib/python3.8/site-packages/jax/core.py", line 1552, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/adnanmunye/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 823, in process
    return trace.process_xmap(self, fun, tracers, params)
  File "/home/adnanmunye/.local/lib/python3.8/site-packages/jax/core.py", line 607, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/adnanmunye/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 644, in xmap_impl
    xmap_callable = make_xmap_callable(
  File "/home/adnanmunye/.local/lib/python3.8/site-packages/jax/linear_util.py", line 262, in memoized_fun
    ans = call(fun, *args)
  File "/home/adnanmunye/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 671, in make_xmap_callable
    _check_out_avals_vs_out_axes(out_avals, out_axes, global_axis_sizes)
  File "/home/adnanmunye/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 1633, in _check_out_avals_vs_out_axes
    raise TypeError(f"One of xmap results has an out_axes specification of "
TypeError: One of xmap results has an out_axes specification of ['batch', ...], but is actually mapped along more axes defined by this xmap call: shard
```
could you please help again?

**Comment by kingoflolz** [comment]
You must use jax==0.2.12, please use init_ray.sh to install the dependencies.
