### ISSUE TITLE
Failed to allocate request for 128.00MiB

### ISSUE THREAD

**Issue by ErikDz** [kingoflolz/mesh-transformer-jax#90]
Hi, I've got a 

- GTX 1080 (8GiB) 
- Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz 
- 32GB of RAm

Is my PC not powerful enough or am I doing something wrong?  I'd be really excited about running this superb model so any tip is greatly appreciated.

```
/home/erikdz/.local/lib/python3.8/site-packages/jax/experimental/maps.py:412: UserWarning: xmap is an experimental feature and probably has bugs!
  warn("xmap is an experimental feature and probably has bugs!")
key shape (1, 2)
in shape (1, 2048)
dp 1
mp 1
2021-08-12 10:19:56.549710: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1981] Execution of replica 0 failed: Resource exhausted: Failed to allocate request for 128.00MiB (134217728B) on device ordinal 0
Traceback (most recent call last):
  File "resharding_example.py", line 50, in <module>
    network = CausalTransformer(params)
  File "/home/erikdz/Documents/startups/social-reach/mesh-transformer-jax/mesh_transformer/transformer_shard.py", line 277, in __init__
    self.state = self.init_xmap(jnp.array(key.take(mp_per_host)), x)
  File "/home/erikdz/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 516, in fun_mapped
    out_flat = xmap_p.bind(
  File "/home/erikdz/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 652, in bind
    return core.call_bind(self, fun, *args, **params)  # type: ignore
  File "/home/erikdz/.local/lib/python3.8/site-packages/jax/core.py", line 1393, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/erikdz/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 655, in process
    return trace.process_xmap(self, fun, tracers, params)
  File "/home/erikdz/.local/lib/python3.8/site-packages/jax/core.py", line 600, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/erikdz/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 539, in xmap_impl
    return make_xmap_callable(fun, name, in_axes, out_axes_thunk, donated_invars, global_axis_sizes,
  File "/home/erikdz/.local/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 1130, in execute_replicated
    out_bufs = compiled.execute_sharded_on_local_devices(input_bufs)
RuntimeError: Resource exhausted: Failed to allocate request for 128.00MiB (134217728B) on device ordinal 0
```

**Comment by maderix** [comment]
I'm getting the same error for some reason :
python resharding_example.py
/opt/conda/lib/python3.7/site-packages/jax/experimental/maps.py:412: UserWarning: xmap is an experimental feature and probably has bugs!
  warn("xmap is an experimental feature and probably has bugs!")
key shape (1, 2)
in shape (1, 2048)
dp 1
mp 1
2021-08-12 18:16:23.302001: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1960] Execution of replica 0 failed: Resource exhausted: Failed to allocate request for 20.18GiB (21670470184B) on device ordinal 0
Traceback (most recent call last):
  File "resharding_example.py", line 50, in <module>
    network = CausalTransformer(params)
  File "/mnt/mesh-transformer-jax/mesh_transformer/transformer_shard.py", line 277, in __init__
    self.state = self.init_xmap(jnp.array(key.take(mp_per_host)), x)
  File "/opt/conda/lib/python3.7/site-packages/jax/experimental/maps.py", line 525, in fun_mapped
    backend=backend)
  File "/opt/conda/lib/python3.7/site-packages/jax/experimental/maps.py", line 652, in bind
    return core.call_bind(self, fun, *args, **params)  # type: ignore
  File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 1393, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/opt/conda/lib/python3.7/site-packages/jax/experimental/maps.py", line 655, in process
    return trace.process_xmap(self, fun, tracers, params)
  File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 600, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/opt/conda/lib/python3.7/site-packages/jax/experimental/maps.py", line 540, in xmap_impl
    axis_resources, resource_env, backend, *in_avals)(*args)
  File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/pxla.py", line 1130, in execute_replicated
    out_bufs = compiled.execute_sharded_on_local_devices(input_bufs)
RuntimeError: Resource exhausted: Failed to allocate request for 20.18GiB (21670470184B) on device ordinal 0

nvidia-smi output:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.32.00    Driver Version: 455.32.00    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 6000     Off  | 00000000:65:00.0 Off |                  Off |
| 68%   85C    P2   261W / 260W |   3794MiB / 24220MiB |     92%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Quadro RTX 6000     Off  | 00000000:B3:00.0 Off |                  Off |
| 33%   45C    P8    22W / 260W |    227MiB / 24219MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |

jax version 0.2.12
jaxlib==0.1.64

I think the vram is enough. Could it be some other issue?

**Comment by kingoflolz** [comment]
@ErikDz as the script mentions, you need 19GB of vram to load the model.

@maderix Are you using the environment variables specified in the script? You can also try upgrading your jaxlib to 0.1.67. If that does not fix it, please open another issue as seems to be distinct from the original issue.
